export const sectors = [
    "Technology",
    "Healthcare",
    "Finance",
    "Education",
    "Energy",
    "Real Estate",
    "Retail",
    "Manufacturing",
    "Transportation",
    "Construction",
    "Food & Beverage",
  ];
  
  export const fundingStages = [
    "Seed",
    "Series A",
    "Series B",
    "Series C",
    "Series D",
    "IPO",
    "Growth",
    "Exit",
  ];

  export const areaofpreference = [
    "Europe",
    "LatAm",
    "US",
    "Global",
    "UK",
    "Australia",
    "Southeast Asia",
    "Israel",
    "Oceania"
  ];


  export const basedInCity = [
    "Wien",
    "Ghent",
    "Oakland",
    "San Francisco",
    "Los Angeles",
    "Palo Alto",
    "Carpinteria",
    "Menlo Park",
    "Burlingame",
    "Toronto",
    "Washington",
    "Paris",
    "Atlanta",
    "Cologne Area",
    "Hamburg",
    "Munich",
    "Berlin",
    "Cologne",
    "Chicago",
    "Wichita",
    "Boston",
    "New York",
    "Stockholm",
    "Dallas",
    "Houston",
    "London",
    "Miami"
  ];
  

  export const techMedium = [
    "Hardware", 
    "Software",
  ]



  export const initialCriteria = {
    investorName: "",
    sector: [],
    fundingStage: [],
    minInvestment: "",
    basedin: [],
    areaofpreference: [],
    basedinCity: [],
    investorFirm: "",
    techMedium: [],
  };



  export const basedIn = [
    {name: 'Afghanistan', type: 'country'},
    {name: 'Alabama', type: 'state'},
    {name: 'Alaska', type: 'state'},
    {name: 'Albania', type: 'country'},
    {name: 'Algeria', type: 'country'},
    {name: 'Andorra', type: 'country'},
    {name: 'Angola', type: 'country'},
    {name: 'Antigua & Deps', type: 'country'},
    {name: 'Argentina', type: 'country'},
    {name: 'Arizona', type: 'state'},
    {name: 'Arkansas', type: 'state'},
    {name: 'Armenia', type: 'country'},
    {name: 'Australia', type: 'country'},
    {name: 'Austria', type: 'country'},
    {name: 'Azerbaijan', type: 'country'},
    {name: 'Bahamas', type: 'country'},
    {name: 'Bahrain', type: 'country'},
    {name: 'Bangladesh', type: 'country'},
    {name: 'Barbados', type: 'country'},
    {name: 'Belarus', type: 'country'},
    {name: 'Belgium', type: 'country'},
    {name: 'Belize', type: 'country'},
    {name: 'Benin', type: 'country'},
    {name: 'Bhutan', type: 'country'},
    {name: 'Bolivia', type: 'country'},
    {name: 'Bosnia Herzegovina', type: 'country'},
    {name: 'Botswana', type: 'country'},
    {name: 'Brazil', type: 'country'},
    {name: 'Brunei', type: 'country'},
    {name: 'Bulgaria', type: 'country'},
    {name: 'Burkina', type: 'country'},
    {name: 'Burundi', type: 'country'},
    {name: 'California', type: 'state'},
    {name: 'Cambodia', type: 'country'},
    {name: 'Cameroon', type: 'country'},
    {name: 'Canada', type: 'country'},
    {name: 'Cape Verde', type: 'country'},
    {name: 'Central African Rep', type: 'country'},
    {name: 'Chad', type: 'country'},
    {name: 'Chile', type: 'country'},
    {name: 'China', type: 'country'},
    {name: 'Colombia', type: 'country'},
    {name: 'Colorado', type: 'state'},
    {name: 'Comoros', type: 'country'},
    {name: 'Congo', type: 'country'},
    {name: 'Congo {Democratic Rep}', type: 'country'},
    {name: 'Connecticut', type: 'state'},
    {name: 'Costa Rica', type: 'country'},
    {name: 'Croatia', type: 'country'},
    {name: 'Cuba', type: 'country'},
    {name: 'Cyprus', type: 'country'},
    {name: 'Czech Republic', type: 'country'},
    {name: 'Delaware', type: 'state'},
    {name: 'Denmark', type: 'country'},
    {name: 'Djibouti', type: 'country'},
    {name: 'Dominica', type: 'country'},
    {name: 'Dominican Republic', type: 'country'},
    {name: 'East Timor', type: 'country'},
    {name: 'Ecuador', type: 'country'},
    {name: 'Egypt', type: 'country'},
    {name: 'El Salvador', type: 'country'},
    {name: 'Equatorial Guinea', type: 'country'},
    {name: 'Eritrea', type: 'country'},
    {name: 'Estonia', type: 'country'},
    {name: 'Ethiopia', type: 'country'},
    {name: 'Fiji', type: 'country'},
    {name: 'Finland', type: 'country'},
    {name: 'Florida', type: 'state'},
    {name: 'France', type: 'country'},
    {name: 'Gabon', type: 'country'},
    {name: 'Gambia', type: 'country'},
    {name: 'Georgia', type: 'country'},
    {name: 'Germany', type: 'country'},
    {name: 'Ghana', type: 'country'},
    {name: 'Greece', type: 'country'},
    {name: 'Grenada', type: 'country'},
    {name: 'Guatemala', type: 'country'},
    {name: 'Guinea', type: 'country'},
    {name: 'Guinea-Bissau', type: 'country'},
    {name: 'Guyana', type: 'country'},
    {name: 'Haiti', type: 'country'},
    {name: 'Hawaii', type: 'state'},
    {name: 'Honduras', type: 'country'},
    {name: 'Hungary', type: 'country'},
    {name: 'Iceland', type: 'country'},
    {name: 'Idaho', type: 'state'},
    {name: 'Illinois', type: 'state'},
    {name: 'India', type: 'country'},
    {name: 'Indiana', type: 'state'},
    {name: 'Indonesia', type: 'country'},
    {name: 'Iowa', type: 'state'},
    {name: 'Iran', type: 'country'},
    {name: 'Iraq', type: 'country'},
    {name: 'Ireland', type: 'country'},
    {name: 'Israel', type: 'country'},
    {name: 'Italy', type: 'country'},
    {name: 'Ivory Coast', type: 'country'},
    {name: 'Jamaica', type: 'country'},
    {name: 'Japan', type: 'country'},
    {name: 'Jordan', type: 'country'},
    {name: 'Kansas', type: 'state'},
    {name: 'Kazakhstan', type: 'country'},
    {name: 'Kentucky', type: 'state'},
    {name: 'Kenya', type: 'country'},
    {name: 'Kiribati', type: 'country'},
    {name: 'Korea North', type: 'country'},
    {name: 'Korea South', type: 'country'},
    {name: 'Kosovo', type: 'country'},
    {name: 'Kuwait', type: 'country'},
    {name: 'Kyrgyzstan', type: 'country'},
    {name: 'Laos', type: 'country'},
    {name: 'Latvia', type: 'country'},
    {name: 'Lebanon', type: 'country'},
    {name: 'Lesotho', type: 'country'},
    {name: 'Liberia', type: 'country'},
    {name: 'Libya', type: 'country'},
    {name: 'Liechtenstein', type: 'country'},
    {name: 'Lithuania', type: 'country'},
    {name: 'Louisiana', type: 'state'},
    {name: 'Luxembourg', type: 'country'},
    {name: 'Macedonia', type: 'country'},
    {name: 'Madagascar', type: 'country'},
    {name: 'Maine', type: 'state'},
    {name: 'Malawi', type: 'country'},
    {name: 'Malaysia', type: 'country'},
    {name: 'Maldives', type: 'country'},
    {name: 'Mali', type: 'country'},
    {name: 'Malta', type: 'country'},
    {name: 'Marshall Islands', type: 'country'},
    {name: 'Maryland', type: 'state'},
    {name: 'Massachusetts', type: 'state'},
    {name: 'Mauritania', type: 'country'},
    {name: 'Mauritius', type: 'country'},
    {name: 'Mexico', type: 'country'},
    {name: 'Michigan', type: 'state'},
    {name: 'Micronesia', type: 'country'},
    {name: 'Minnesota', type: 'state'},
    {name: 'Mississippi', type: 'state'},
    {name: 'Missouri', type: 'state'},
    {name: 'Moldova', type: 'country'},
    {name: 'Monaco', type: 'country'},
    {name: 'Mongolia', type: 'country'},
    {name: 'Montana', type: 'state'},
    {name: 'Montenegro', type: 'country'},
    {name: 'Morocco', type: 'country'},
    {name: 'Mozambique', type: 'country'},
    {name: 'Myanmar, {Burma}', type: 'country'},
    {name: 'Namibia', type: 'country'},
    {name: 'Nauru', type: 'country'},
    {name: 'Nebraska', type: 'state'},
    {name: 'Nepal', type: 'country'},
    {name: 'Netherlands', type: 'country'},
    {name: 'Nevada', type: 'state'},
    {name: 'New Hampshire', type: 'state'},
    {name: 'New Jersey', type: 'state'},
    {name: 'New Mexico', type: 'state'},
    {name: 'New York', type: 'state'},
    {name: 'New Zealand', type: 'country'},
    {name: 'Nicaragua', type: 'country'},
    {name: 'Niger', type: 'country'},
    {name: 'Nigeria', type: 'country'},
    {name: 'North Carolina', type: 'state'},
    {name: 'North Dakota', type: 'state'},
    {name: 'Norway', type: 'country'},
    {name: 'Ohio', type: 'state'},
    {name: 'Oklahoma', type: 'state'},
    {name: 'Oman', type: 'country'},
    {name: 'Oregon', type: 'state'},
    {name: 'Pakistan', type: 'country'},
    {name: 'Palau', type: 'country'},
    {name: 'Panama', type: 'country'},
    {name: 'Papua New Guinea', type: 'country'},
    {name: 'Paraguay', type: 'country'},
    {name: 'Pennsylvania', type: 'state'},
    {name: 'Peru', type: 'country'},
    {name: 'Philippines', type: 'country'},
    {name: 'Poland', type: 'country'},
    {name: 'Portugal', type: 'country'},
    {name: 'Qatar', type: 'country'},
    {name: 'Rhode Island', type: 'state'},
    {name: 'Romania', type: 'country'},
    {name: 'Russian Federation', type: 'country'},
    {name: 'Rwanda', type: 'country'},
    {name: 'Saint Vincent & the Grenadines', type: 'country'},
    {name: 'Samoa', type: 'country'},
    {name: 'San Marino', type: 'country'},
    {name: 'Sao Tome & Principe', type: 'country'},
    {name: 'Saudi Arabia', type: 'country'},
    {name: 'Senegal', type: 'country'},
    {name: 'Serbia', type: 'country'},
    {name: 'Seychelles', type: 'country'},
    {name: 'Sierra Leone', type: 'country'},
    {name: 'Singapore', type: 'country'},
    {name: 'Slovakia', type: 'country'},
    {name: 'Slovenia', type: 'country'},
    {name: 'Solomon Islands', type: 'country'},
    {name: 'Somalia', type: 'country'},
    {name: 'South Africa', type: 'country'},
    {name: 'South Carolina', type: 'state'},
    {name: 'South Dakota', type: 'state'},
    {name: 'South Sudan', type: 'country'},
    {name: 'Spain', type: 'country'},
    {name: 'Sri Lanka', type: 'country'},
    {name: 'St Kitts & Nevis', type: 'country'},
    {name: 'St Lucia', type: 'country'},
    {name: 'Sudan', type: 'country'},
    {name: 'Suriname', type: 'country'},
    {name: 'Swaziland', type: 'country'},
    {name: 'Sweden', type: 'country'},
    {name: 'Switzerland', type: 'country'},
    {name: 'Syria', type: 'country'},
    {name: 'Taiwan', type: 'country'},
    {name: 'Tajikistan', type: 'country'},
    {name: 'Tanzania', type: 'country'},
    {name: 'Tennessee', type: 'state'},
    {name: 'Texas', type: 'state'},
    {name: 'Thailand', type: 'country'},
    {name: 'Togo', type: 'country'},
    {name: 'Tonga', type: 'country'},
    {name: 'Trinidad & Tobago', type: 'country'},
    {name: 'Tunisia', type: 'country'},
    {name: 'Turkey', type: 'country'},
    {name: 'Turkmenistan', type: 'country'},
    {name: 'Tuvalu', type: 'country'},
    {name: 'Uganda', type: 'country'},
    {name: 'Ukraine', type: 'country'},
    {name: 'United Arab Emirates', type: 'country'},
    {name: 'United Kingdom', type: 'country'},
    {name: 'United States', type: 'country'},
    {name: 'Uruguay', type: 'country'},
    {name: 'Utah', type: 'state'},
    {name: 'Uzbekistan', type: 'country'},
    {name: 'Vanuatu', type: 'country'},
    {name: 'Vatican City', type: 'country'},
    {name: 'Venezuela', type: 'country'},
    {name: 'Vermont', type: 'state'},
    {name: 'Vietnam', type: 'country'},
    {name: 'Virginia', type: 'state'},
    {name: 'Washington, D.C.', type: 'state'},
    {name: 'West Virginia', type: 'state'},
    {name: 'Wisconsin', type: 'state'},
    {name: 'Wyoming', type: 'state'},
    {name: 'Yemen', type: 'country'},
    {name: 'Zambia', type: 'country'},
    {name: 'Zimbabwe', type: 'country'}]
  