export const sectors = [
  'AI', 'Affordability', 'Aging Population', 'Agriculture', 'Applied ML & AI', 
  'Architecture', 'Automation', 'B2B', 'B2C', 'Building Material', 
  'Clean Tech', 'Climate Resilience', 'Climate Tech', 'Commercial', 'ConTech', 
  'Construction', 'Creator Economy', 'Credit & Insurance', 'Data Analytics', 
  'Decarbonization', 'DeepTech', 'Digital Twin', 'Digitalization', 'ESG', 
  'Electrification', 'Enterprise', 'Farmland', 'Fintech', 'Future of Work', 
  'Generative AI', 'Green Energy', 'HealthTech', 'Housing Shortage', 
  'Industrial', 'Infrastructure', 'IoT', 'Labor Shortage', 'Leisure', 
  'Lending Tech', 'Machine Learning', 'Material Procurement', 'Mobility', 
  'Modular Components', 'Mortgage Tech', 'Multifamily', 'OpCo', 'PropCo', 
  'PropTech', 'PropTech Agnostic', 'Renewable Energy', 'Residential', 
  'Retrofit Tech', 'Robotics', 'Saas', 'Single Family', 'Smart Buildings', 
  'Software', 'Sustainability', 'Web3', 'Web3/Blockchain', 'Workflow Automation', 
  'iBuying'
]
;
  
  export const fundingStages = [
    "Pre-Seed",
    "Seed",
    "A",
    "B",
    "C",
    "D",
    "IPO",
    "Agnostic",
  ];

  export const areaofpreference = [
    "Europe",
    "LatAm",
    "US",
    "Global",
    "UK",
    "Australia",
    "Southeast Asia",
    "Israel",
    "Oceania"
  ];


  export const basedInCity = [
    "Wien",
    "Ghent",
    "Oakland",
    "San Francisco",
    "Los Angeles",
    "Palo Alto",
    "Carpinteria",
    "Menlo Park",
    "Burlingame",
    "Toronto",
    "Washington",
    "Paris",
    "Atlanta",
    "Cologne Area",
    "Hamburg",
    "Munich",
    "Berlin",
    "Cologne",
    "Chicago",
    "Wichita",
    "Boston",
    "New York",
    "Stockholm",
    "Dallas",
    "Houston",
    "London",
    "Miami"
  ];
  

  export const techMedium = [
    "Hardware", 
    "Software",
  ]



  export const initialCriteria = {
    investorName: "",
    sector: [],
    fundingStage: [],
    minInvestment: "",
    basedin: [],
    areaofpreference: [],
    basedinCity: [],
    investorFirm: "",
    techMedium: [],
  };



  export const basedIn = [
    {name: 'AL', type: 'state', flag: 'us'},
    {name: 'AK', type: 'state', flag: 'us'},
    {name: 'AZ', type: 'state', flag: 'us'},
    {name: 'AR', type: 'state', flag: 'us'},
    {name: 'CO', type: 'state', flag: 'us'},
    {name: 'CT', type: 'state', flag: 'us'},
    {name: 'DE', type: 'state', flag: 'us'},
    {name: 'FL', type: 'state', flag: 'us'},
    {name: 'GA', type: 'state', flag: 'us'},
    {name: 'HI', type: 'state', flag: 'us'},
    {name: 'IA', type: 'state', flag: 'us'},
    {name: 'ID', type: 'state', flag: 'us'},
    {name: 'IL', type: 'state', flag: 'us'},
    {name: 'IN', type: 'state', flag: 'us'},
    {name: 'KS', type: 'state', flag: 'us'},
    {name: 'KY', type: 'state', flag: 'us'},
    {name: 'LA', type: 'state', flag: 'us'},
    {name: 'MA', type: 'state', flag: 'us'},
    {name: 'MD', type: 'state', flag: 'us'},
    {name: 'ME', type: 'state', flag: 'us'},
    {name: 'MI', type: 'state', flag: 'us'},
    {name: 'MN', type: 'state', flag: 'us'},
    {name: 'MO', type: 'state', flag: 'us'},
    {name: 'MS', type: 'state', flag: 'us'},
    {name: 'MT', type: 'state', flag: 'us'},
    {name: 'NE', type: 'state', flag: 'us'},
    {name: 'NV', type: 'state', flag: 'us'},
    {name: 'NH', type: 'state', flag: 'us'},
    {name: 'NJ', type: 'state', flag: 'us'},
    {name: 'NM', type: 'state', flag: 'us'},
    {name: 'NY', type: 'state', flag: 'us'},
    {name: 'NC', type: 'state', flag: 'us'},
    {name: 'ND', type: 'state', flag: 'us'},
    {name: 'OH', type: 'state', flag: 'us'},
    {name: 'OK', type: 'state', flag: 'us'},
    {name: 'OR', type: 'state', flag: 'us'},
    {name: 'PA', type: 'state', flag: 'us'},
    {name: 'RI', type: 'state', flag: 'us'},
    {name: 'SC', type: 'state', flag: 'us'},
    {name: 'SD', type: 'state', flag: 'us'},
    {name: 'TN', type: 'state', flag: 'us'},
    {name: 'TX', type: 'state', flag: 'us'},
    {name: 'UT', type: 'state', flag: 'us'},
    {name: 'VA', type: 'state', flag: 'us'},
    {name: 'WA', type: 'state', flag: 'us'},
    {name: 'WV', type: 'state', flag: 'us'},
    {name: 'WI', type: 'state', flag: 'us'},
    {name: 'WY', type: 'state', flag: 'us'},
      {name: 'Afghanistan', type: 'country', flag: 'af'},
      {name: 'Albania', type: 'country', flag: 'al'},
      {name: 'Algeria', type: 'country', flag: 'dz'},
      {name: 'Andorra', type: 'country', flag: 'ad'},
      {name: 'Angola', type: 'country', flag: 'ao'},
      {name: 'Antigua and Barbuda', type: 'country', flag: 'ag'},
      {name: 'Argentina', type: 'country', flag: 'ar'},
      {name: 'Armenia', type: 'country', flag: 'am'},
      {name: 'Australia', type: 'country', flag: 'au'},
      {name: 'Austria', type: 'country', flag: 'at'},
      {name: 'Azerbaijan', type: 'country', flag: 'az'},
      {name: 'Bahamas', type: 'country', flag: 'bs'},
      {name: 'Bahrain', type: 'country', flag: 'bh'},
      {name: 'Bangladesh', type: 'country', flag: 'bd'},
      {name: 'Barbados', type: 'country', flag: 'bb'},
      {name: 'Belarus', type: 'country', flag: 'by'},
      {name: 'Belgium', type: 'country', flag: 'be'},
      {name: 'Belize', type: 'country', flag: 'bz'},
      {name: 'Benin', type: 'country', flag: 'bj'},
      {name: 'Bhutan', type: 'country', flag: 'bt'},
      {name: 'Bolivia', type: 'country', flag: 'bo'},
      {name: 'Bosnia and Herzegovina', type: 'country', flag: 'ba'},
      {name: 'Botswana', type: 'country', flag: 'bw'},
      {name: 'Brazil', type: 'country', flag: 'br'},
      {name: 'Brunei', type: 'country', flag: 'bn'},
      {name: 'Bulgaria', type: 'country', flag: 'bg'},
      {name: 'Burkina Faso', type: 'country', flag: 'bf'},
      {name: 'Burundi', type: 'country', flag: 'bi'},
      {name: 'Cabo Verde', type: 'country', flag: 'cv'},
      {name: 'Cambodia', type: 'country', flag: 'kh'},
      {name: 'Cameroon', type: 'country', flag: 'cm'},
      {name: 'Canada', type: 'country', flag: 'ca'},
      {name: 'Central African Republic', type: 'country', flag: 'cf'},
      {name: 'Chad', type: 'country', flag: 'td'},
      {name: 'Chile', type: 'country', flag: 'cl'},
      {name: 'China', type: 'country', flag: 'cn'},
      {name: 'Colombia', type: 'country', flag: 'co'},
      {name: 'Comoros', type: 'country', flag: 'km'},
      {name: 'Congo (Congo-Brazzaville)', type: 'country', flag: 'cg'},
      {name: 'Congo (Democratic Republic of the Congo)', type: 'country', flag: 'cd'},
      {name: 'Costa Rica', type: 'country', flag: 'cr'},
      {name: 'Croatia', type: 'country', flag: 'hr'},
      {name: 'Cuba', type: 'country', flag: 'cu'},
      {name: 'Cyprus', type: 'country', flag: 'cy'},
      {name: 'Czechia (Czech Republic)', type: 'country', flag: 'cz'},
      {name: 'Denmark', type: 'country', flag: 'dk'},
      {name: 'Djibouti', type: 'country', flag: 'dj'},
      {name: 'Dominica', type: 'country', flag: 'dm'},
      {name: 'Dominican Republic', type: 'country', flag: 'do'},
      {name: 'Ecuador', type: 'country', flag: 'ec'},
      {name: 'Egypt', type: 'country', flag: 'eg'},
      {name: 'El Salvador', type: 'country', flag: 'sv'},
      {name: 'Equatorial Guinea', type: 'country', flag: 'gq'},
      {name: 'Eritrea', type: 'country', flag: 'er'},
      {name: 'Estonia', type: 'country', flag: 'ee'},
      {name: 'Eswatini', type: 'country', flag: 'sz'},
      {name: 'Ethiopia', type: 'country', flag: 'et'},
      {name: 'Fiji', type: 'country', flag: 'fj'},
      {name: 'Finland', type: 'country', flag: 'fi'},
      {name: 'France', type: 'country', flag: 'fr'},
      {name: 'Gabon', type: 'country', flag: 'ga'},
      {name: 'Gambia', type: 'country', flag: 'gm'},
      {name: 'Georgia', type: 'country', flag: 'ge'},
      {name: 'Germany', type: 'country', flag: 'de'},
      {name: 'Ghana', type: 'country', flag: 'gh'},
      {name: 'Greece', type: 'country', flag: 'gr'},
      {name: 'Grenada', type: 'country', flag: 'gd'},
      {name: 'Guatemala', type: 'country', flag: 'gt'},
      {name: 'Guinea', type: 'country', flag: 'gn'},
      {name: 'Guinea-Bissau', type: 'country', flag: 'gw'},
      {name: 'Guyana', type: 'country', flag: 'gy'},
      {name: 'Haiti', type: 'country', flag: 'ht'},
      {name: 'Honduras', type: 'country', flag: 'hn'},
      {name: 'Hungary', type: 'country', flag: 'hu'},
      {name: 'Iceland', type: 'country', flag: 'is'},
      {name: 'India', type: 'country', flag: 'in'},
      {name: 'Indonesia', type: 'country', flag: 'id'},
      {name: 'Iran', type: 'country', flag: 'ir'},
      {name: 'Iraq', type: 'country', flag: 'iq'},
      {name: 'Ireland', type: 'country', flag: 'ie'},
      {name: 'Israel', type: 'country', flag: 'il'},
      {name: 'Italy', type: 'country', flag: 'it'},
      {name: 'Jamaica', type: 'country', flag: 'jm'},
      {name: 'Japan', type: 'country', flag: 'jp'},
      {name: 'Jordan', type: 'country', flag: 'jo'},
      {name: 'Kazakhstan', type: 'country', flag: 'kz'},
      {name: 'Kenya', type: 'country', flag: 'ke'},
      {name: 'Kiribati', type: 'country', flag: 'ki'},
      {name: 'Korea (North)', type: 'country', flag: 'kp'},
      {name: 'Korea (South)', type: 'country', flag: 'kr'},
      {name: 'Kuwait', type: 'country', flag: 'kw'},
      {name: 'Kyrgyzstan', type: 'country', flag: 'kg'},
      {name: 'Laos', type: 'country', flag: 'la'},
      {name: 'Latvia', type: 'country', flag: 'lv'},
      {name: 'Lebanon', type: 'country', flag: 'lb'},
      {name: 'Lesotho', type: 'country', flag: 'ls'},
      {name: 'Liberia', type: 'country', flag: 'lr'},
      {name: 'Libya', type: 'country', flag: 'ly'},
      {name: 'Liechtenstein', type: 'country', flag: 'li'},
      {name: 'Lithuania', type: 'country', flag: 'lt'},
      {name: 'Luxembourg', type: 'country', flag: 'lu'},
      {name: 'Madagascar', type: 'country', flag: 'mg'},
      {name: 'Malawi', type: 'country', flag: 'mw'},
      {name: 'Malaysia', type: 'country', flag: 'my'},
      {name: 'Maldives', type: 'country', flag: 'mv'},
      {name: 'Mali', type: 'country', flag: 'ml'},
      {name: 'Malta', type: 'country', flag: 'mt'},
      {name: 'Marshall Islands', type: 'country', flag: 'mh'},
      {name: 'Mauritania', type: 'country', flag: 'mr'},
      {name: 'Mauritius', type: 'country', flag: 'mu'},
      {name: 'Mexico', type: 'country', flag: 'mx'},
      {name: 'Micronesia', type: 'country', flag: 'fm'},
      {name: 'Moldova', type: 'country', flag: 'md'},
      {name: 'Monaco', type: 'country', flag: 'mc'},
      {name: 'Mongolia', type: 'country', flag: 'mn'},
      {name: 'Montenegro', type: 'country', flag: 'me'},
      {name: 'Morocco', type: 'country', flag: 'ma'},
      {name: 'Mozambique', type: 'country', flag: 'mz'},
      {name: 'Myanmar (Burma)', type: 'country', flag: 'mm'},
      {name: 'Namibia', type: 'country', flag: 'na'},
      {name: 'Nauru', type: 'country', flag: 'nr'},
      {name: 'Nepal', type: 'country', flag: 'np'},
      {name: 'Netherlands', type: 'country', flag: 'nl'},
      {name: 'New Zealand', type: 'country', flag: 'nz'},
      {name: 'Nicaragua', type: 'country', flag: 'ni'},
      {name: 'Niger', type: 'country', flag: 'ne'},
      {name: 'Nigeria', type: 'country', flag: 'ng'},
      {name: 'North Macedonia', type: 'country', flag: 'mk'},
      {name: 'Norway', type: 'country', flag: 'no'},
      {name: 'Oman', type: 'country', flag: 'om'},
      {name: 'Pakistan', type: 'country', flag: 'pk'},
      {name: 'Palau', type: 'country', flag: 'pw'},
      {name: 'Panama', type: 'country', flag: 'pa'},
      {name: 'Papua New Guinea', type: 'country', flag: 'pg'},
      {name: 'Paraguay', type: 'country', flag: 'py'},
      {name: 'Peru', type: 'country', flag: 'pe'},
      {name: 'Philippines', type: 'country', flag: 'ph'},
      {name: 'Poland', type: 'country', flag: 'pl'},
      {name: 'Portugal', type: 'country', flag: 'pt'},
      {name: 'Qatar', type: 'country', flag: 'qa'},
      {name: 'Romania', type: 'country', flag: 'ro'},
      {name: 'Russia', type: 'country', flag: 'ru'},
      {name: 'Rwanda', type: 'country', flag: 'rw'},
      {name: 'Saint Kitts and Nevis', type: 'country', flag: 'kn'},
      {name: 'Saint Lucia', type: 'country', flag: 'lc'},
      {name: 'Saint Vincent and the Grenadines', type: 'country', flag: 'vc'},
      {name: 'Samoa', type: 'country', flag: 'ws'},
      {name: 'San Marino', type: 'country', flag: 'sm'},
      {name: 'Sao Tome and Principe', type: 'country', flag: 'st'},
      {name: 'Saudi Arabia', type: 'country', flag: 'sa'},
      {name: 'Senegal', type: 'country', flag: 'sn'},
      {name: 'Serbia', type: 'country', flag: 'rs'},
      {name: 'Seychelles', type: 'country', flag: 'sc'},
      {name: 'Sierra Leone', type: 'country', flag: 'sl'},
      {name: 'Singapore', type: 'country', flag: 'sg'},
      {name: 'Slovakia', type: 'country', flag: 'sk'},
      {name: 'Slovenia', type: 'country', flag: 'si'},
      {name: 'Solomon Islands', type: 'country', flag: 'sb'},
      {name: 'Somalia', type: 'country', flag: 'so'},
      {name: 'South Africa', type: 'country', flag: 'za'},
      {name: 'South Sudan', type: 'country', flag: 'ss'},
      {name: 'Spain', type: 'country', flag: 'es'},
      {name: 'Sri Lanka', type: 'country', flag: 'lk'},
      {name: 'Sudan', type: 'country', flag: 'sd'},
      {name: 'Suriname', type: 'country', flag: 'sr'},
      {name: 'Sweden', type: 'country', flag: 'se'},
      {name: 'Switzerland', type: 'country', flag: 'ch'},
      {name: 'Syria', type: 'country', flag: 'sy'},
      {name: 'Taiwan', type: 'country', flag: 'tw'},
      {name: 'Tajikistan', type: 'country', flag: 'tj'},
      {name: 'Tanzania', type: 'country', flag: 'tz'},
      {name: 'Thailand', type: 'country', flag: 'th'},
      {name: 'Timor-Leste', type: 'country', flag: 'tl'},
      {name: 'Togo', type: 'country', flag: 'tg'},
      {name: 'Tonga', type: 'country', flag: 'to'},
      {name: 'Trinidad and Tobago', type: 'country', flag: 'tt'},
      {name: 'Tunisia', type: 'country', flag: 'tn'},
      {name: 'Turkey', type: 'country', flag: 'tr'},
      {name: 'Turkmenistan', type: 'country', flag: 'tm'},
      {name: 'Tuvalu', type: 'country', flag: 'tv'},
      {name: 'Uganda', type: 'country', flag: 'ug'},
      {name: 'Ukraine', type: 'country', flag: 'ua'},
      {name: 'United Arab Emirates', type: 'country', flag: 'ae'},
      {name: 'United Kingdom', type: 'country', flag: 'gb'},
      {name: 'United States', type: 'country', flag: 'us'},
      {name: 'Uruguay', type: 'country', flag: 'uy'},
      {name: 'Uzbekistan', type: 'country', flag: 'uz'},
      {name: 'Vanuatu', type: 'country', flag: 'vu'},
      {name: 'Vatican City', type: 'country', flag: 'va'},
      {name: 'Venezuela', type: 'country', flag: 've'},
      {name: 'Vietnam', type: 'country', flag: 'vn'},
      {name: 'Yemen', type: 'country', flag: 'ye'},
      {name: 'Zambia', type: 'country', flag: 'zm'},
      {name: 'Zimbabwe', type: 'country', flag: 'zw'}
  ];
